In [1]:
import numpy as np
import pandas as pd 
from sklearn.datasets import make_blobs#产生聚类算法的模拟数据
from sklearn.cluster import KMeans

In [28]:
# 1 产生模拟数据make_blob()
#n_samples是待生成的样本的总数。
#n_features是每个样本的特征数。
#centers表示类别数。
#cluster_std表示每个类别的方差，例如我们希望生成2类数据，其中一类比另一类具有更大的方差，可以将cluster_std设置为[1.0,3.0]。

#返回值2个
#1.1生成的样本数据集。 

#2.2样本数据集的标签。
X,Y = make_blobs(n_samples=2000,n_features=3,centers=4,random_state=0)
Y

array([2, 3, 1, ..., 0, 3, 1])

In [20]:
# 构建模型 
km = KMeans(n_clusters=4,max_iter= 400,init='random',random_state=0)
#KMeans()参数解释
'''
1.n_clusters 聚类的数目 即产生的质心数
2.max_iter 执行一次k-means算法的最大迭代次数，k-means算法 的迭代过程：给定质心坐标，计算所有样本到
质心坐标的距离，然后移动质心坐标 在计算样本到质心坐标的距离，直到找到最好的
3.n_init用不同的质心初始化值 运行算法的次数。第一次 的质心坐标是随机给的
4.init  执行初始化质心的方式’k-means++’， ‘random’，或者传递一个ndarray向量
5.precompute_distance 预计算距离 三个可选值，‘auto’，True 或者 False
一般 选择‘auto’如果样本数 *  聚类数> 12million 则不预计算，也就是false

其他参数  用到时 在查询tol，n_jobs，copy_x：

'''
km.fit(X)

KMeans(algorithm='auto', copy_x=True, init='random', max_iter=400,
    n_clusters=4, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=0, tol=0.0001, verbose=0)

In [21]:
y_pre = km.predict(X)

In [22]:
km.score(X)#样本点到其簇中心的距离之和 的相反数

-5718.664069490822

In [23]:
#KMeans() 的方法
print('簇中心坐标：')
print(km.cluster_centers_)

簇中心坐标：
[[-1.24244014  7.83967363  9.21825877]
 [-2.40147224  5.88015134  0.62973665]
 [ 0.95948665  4.29519314  1.98661316]
 [ 0.90193297 -1.57623651  2.87903628]]


In [24]:
print('每个样本的分类：')
print(km.labels_)

每个样本的分类：
[0 1 3 ... 2 2 3]


In [29]:
print('每一个点到其簇中心的距离之和：')
print(km.inertia_)

每一个点到其簇中心的距离之和：
5718.66406949082
